# Generated by Django 4.1.5 on 2023-01-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('numero', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('longr', models.FloatField()),
                ('largr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id_checkpoint', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_batiment', models.IntegerField()),
                ('id_etage', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('numero', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id_batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imap_api.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imap_api.batiment')),
                ('numero_etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imap_api.etage')),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longr', models.FloatField()),
                ('direction', models.CharField(max_length=2)),
                ('id_cp_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cp_destination', to='imap_api.checkpoint')),
                ('id_cp_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cp_origine', to='imap_api.checkpoint')),
            ],
        ),
    ]
