# Generated by Django 4.1.5 on 2023-01-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imap_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='id_batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imap_api.batiment'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='id_etage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imap_api.etage'),
        ),
    ]
