# Generated by Django 4.1.5 on 2023-01-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imap_api', '0002_alter_checkpoint_id_batiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='direction',
            new_name='direction_origine',
        ),
        migrations.AlterField(
            model_name='cable',
            name='id_cp_origine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cp_origine', to='imap_api.checkpoint'),
        ),
    ]
